// Host reloads mid-game: the table must come back and the guest must resync.
import { chromium } from 'playwright-core';
const base = process.argv[2] || 'http://127.0.0.1:5199/';
const b = await chromium.launch({ channel: 'chrome', headless: true });
const mk = async () => (await b.newContext({ viewport: { width: 900, height: 700 } })).newPage();
const host = await mk(), guest = await mk();
await host.goto(base);
await host.fill('#name-input', 'César');
await host.click('.action:nth-of-type(2)');
await host.waitForSelector('.room-code');
const code = (await host.textContent('.room-code')).trim();
await guest.goto(`${base}#/m/${code}`);
await guest.fill('#gate-name', 'Pai');
await guest.click('.who .btn.primary');
await guest.waitForSelector('.lobby', { timeout: 30000 });
await host.waitForTimeout(800);
await host.click('.lobby-foot .btn.primary');
await guest.waitForSelector('.game', { timeout: 15000 });
await host.waitForTimeout(3000);
const t0 = Date.now();
await host.reload();
await host.waitForSelector('.game', { timeout: 20000 });
console.log('host table restored in', Date.now() - t0, 'ms');
await host.waitForTimeout(1500);
await host.click('.emote-wrap .icon-btn');
await host.fill('.chat-row input', 'voltei!');
await host.click('.chat-row .btn');
const t1 = Date.now();
await guest.waitForSelector('.bubble:has-text("voltei!")', { timeout: 30000 });
console.log('guest received message from reloaded host after', Date.now() - t1, 'ms');
await b.close();
